name: Mirror Sub-packages

on:
  push:
    branches:
      - master
    paths:
        # Only run when files in these specific folders change
      - 'packages/**'
  workflow_dispatch:

jobs:
  mirror_action_trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push Action Trigger
        run: |
          git config --unset-all http.https://github.com/.extraheader
          git subtree push --prefix packages/tableau-action-trigger https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/biztory/n8n-nodes-autom8-tableau-action-trigger.git master
    permissions:
      deployments: write
      contents: write
      statuses: write
      actions: write
      checks: read

  mirror_alert_trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push Alert Trigger
        run: |
          git config --unset-all http.https://github.com/.extraheader
          git subtree push --prefix packages/tableau-alert-trigger https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/biztory/n8n-nodes-autom8-tableau-alert-trigger.git master
    permissions:
      deployments: write
      contents: write
      statuses: write
      actions: write
      checks: read